[project]
name = "specfem2d"
version = "0.1.0"
description = "SPECFEM2D-pixi"
channels = ["gimli","conda-forge"]
platforms = ["linux-64"]

[system-requirements]
#linux = "4.18"

[tasks]
# setting environment variables add to bash config file and path
specfem_root = """grep -q '^export SPECFEM2D_ROOT=' "$HOME/.bashrc" && sed -i "/^export SPECFEM2D_ROOT=/c\\export SPECFEM2D_ROOT=$(pwd)" "$HOME/.bashrc" || echo 'export SPECFEM2D_ROOT='$(pwd) >> "$HOME/.bashrc""""
add_to_path = """echo 'if [[ ":$PATH:" != *":$SPECFEM2D_ROOT:"* ]]; then export PATH="$SPECFEM2D_ROOT:$PATH"; fi' >> "$HOME/.bashrc""""
knots = """source $HOME/.bashrc"""
envs = { depends_on = ["specfem_root", "add_to_path"]}

#configure and install
configure = { cmd = "./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi=yes", depends_on = "envs" }
install = { cmd = "make -j 4", depends_on = "configure"}

#check installation by running the example
example = "./run_this_example.sh"

[dependencies]
gmsh = ">=4.12.2,<4.13"
pygimli = ">=1.5.0,<1.6"
make = ">=4.3,<5"
