[project]
name = "specfem2d"
version = "0.1.0"
description = "SPECFEM2D-pixi"
channels = ["gimli","conda-forge"]
platforms = ["linux-64"]

[system-requirements]
#linux = "4.18"

[tasks]
# setting environment variables
specfem_root = "export SPECFEM2D_ROOT = $pwd"
add_to_path = "export PATH = $PATH:$SPECFEM2D_ROOT/bin:."
envs = { depends_on = ["specfem_root", "add_to_path"]}

#configure and install
configure = { cmd = "./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi=yes", depends_on = "envs" }
install = { cmd = "make -j 4", depends_on = "configure"}

#check installation by running the example
example = "./run_this_example.sh"

[dependencies]
gmsh = ">=4.12.2,<4.13"
pygimli = ">=1.5.0,<1.6"
make = ">=4.3,<5"
